name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos
    steps:
    - uses: actions/checkout@v2

    - name: Install Tuist 🛠
      run: mise install tuist
      
    - name: fetch Xcode project with Tuist
      run: tuist fetch

    - name: Generate Xcode project with Tuist
      run: tuist generate

    - name: Cache Tuist Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.tuist
        key: ${{ runner.os }}-tuist-${{ hashFiles('**/Project.swift') }}
        restore-keys: |
          ${{ runner.os }}-tuist-
      

    - name: Start xcode build and test 🛠
      run: |
        set -o pipefail && xcodebuild clean build -scheme TuistTest -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2'

